name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}


    - name: Validate composer.json and composer.lock
      uses: php-actions/composer@v5
      with:
        command: validate
        php_version: ${{ matrix.php-versions }}
        version: 1

    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        command: install
        args: --prefer-dist --no-progress --no-suggest --verbose
        php_version: ${{ matrix.php-versions }}
        version: 1

    - name: Format
      uses: php-actions/composer@v5
      with:
        command: run-script format
        php_version: ${{ matrix.php-versions }}
        version: 1

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      # Skip testing on PHP 7.4, because php-mock required by PHP 5.6 breaks on 7.4+
      if: matrix.php-versions < '7.4'
      uses: php-actions/composer@v5
      with:
        command: run-script test
        php_version: ${{ matrix.php-versions }}
        version: 1
